### ISSUE TITLE
Lightning-datatable component example

### ISSUE THREAD

**Issue by briannabrownOE** [trailheadapps/lwc-recipes#172]
**What is missing from the application? Please describe.**
I'd like to see an implementation of a `lightning-datatable` in the recipes app. I'm featuring quite a few `lightning-datatables` throughout the LWCs i've been building for my org. While there are examples of `lightning-datatables` in the other `trailheadapps` repos, `test.js` files are not included. I'm specifically struggling to determine the syntax that is needed to use the `querySelector` to attain information about the data that is being populated in the table. For example, I'm trying to write a jest test that confirms when rows are selected in the table an event is fired. I'm not sure how to simulate this in my tests.

**Describe the solution you'd like**
Create an additional `LWC` component that features a `lightning-datatable` with `rowselection` enabled and `inline editing` options.

**Describe alternatives you've considered**
I've gotten stuck a couple of times trying to figure out why my datatable is not displaying results in the way that i'd expect, and resorted to creating an Aura component in it's stead.

**Comment by miteshmsharma** [comment]
Implementing row record action should solve the problem but I am sure this
is not right forum for such issues. This forum as I understand it is
primarily for lwc engine and component rendering issues.

**Comment by muenzpraeger** [comment]
@briannabrownOE That is not how to approach a unit test.

In a unit test you test the behavior of your own component. The internal implementation of any component that you use is an implementation detail of said component, and not relevant to your tests.

Even if we would add a `lightning-datatable` example in this repo, which is out of scope as this repo focuses on general LWC techniques, it would not bring the from you expected result. The reason is that the mock implementation for `lightning-datatable` [here](https://github.com/salesforce/sfdx-lwc-jest/tree/master/src/lightning-stubs/datatable) is just, well, a mock. Which is sufficient for unit testing.
