### ISSUE TITLE
NavigationMixin callback

### ISSUE THREAD

**Issue by elmerhd** [trailheadapps/lwc-recipes#228]
this[NavigationMixin.Navigate]({
            type: 'standard__recordPage',
            attributes: {
                recordId: timeEntryId,
                objectApiName: 'Time_Entry__c',
                actionName: 'edit'
            }
        })

how do we know if the user clicked saved or cancel?

**Comment by pchittum** [comment]
@elmerhd, I'd suggest asking this question on salesforce.stackexchange.com. I see what you're talking about, but don't see any documentation stating support for `NavigationMixin.Navigate` to take a callback. 

This repo here is specifically for fixes to the actual recipes we implement, and since this doesn't appear to be possible right now, there wouldn't be a recipe to include. 

Thanks!
