### ISSUE TITLE
Everything with https://developer.salesforce.com/docs/component-library/documentation/lwc/lwc.create_third_party_library

### ISSUE THREAD

**Issue by TannerJuby1** [trailheadapps/lwc-recipes#68]
I tried following [this](https://developer.salesforce.com/docs/component-library/documentation/lwc/lwc.create_third_party_library) documentation to display the graph in the example, and am running into error after error after error. 

Here is a list of all the issues I've had:

- Downloading the zip file and uploading as a static resource does not work as you suggest. You have to get the specific files you want and compress them together as a group. You can't compress the folder hosting the files and upload that. Please document this.
- You import the D3 resource as `D3` but then attempt to use `d3` all throughout the `initializeD3` method. 
- In the `renderedCallback` method, you put `error.body.message` as the message to the toast event, but I continually get the error `undefined is not an object`. This catch does cannot handle the errors that occurs in the `initializeD3` method.
- In the `initializeD3` method, I can't get past the first line `const svg = D3.select(this.template.querySelector('svg.d3'))` line because I get the error `e.select is not a function. 'e.select' is not a method`. To confirm this, I went into your `d3.v5.min.js` file in [this directory](https://github.com/trailheadapps/lwc-recipes/tree/master/force-app/main/default/staticresources/d3) and sure enough, the `select` function is non-existent...
- I then tried to get the main `d3.js` file from d3js.org website and use that instead, but I still get the error.

Can you please update your documentation so that is doesn't send everyone down a rabbit hole of errors? It's pretty frustrating being told how to do something by the mainline resource of Salesforce and all those steps do is lead you to error after error...

All I want is to get D3JS to work with my salesforce app but all I get is errors.... Using your documentation, I attempted to just upload D3's `d3.js` file from their latest release, and turns out none of the functions work. `.select`, `.scaleOrdinal`, `.forceSimulation`, etc. all of these are `undefined`.... What could possibly be the issue that my Web Component is unable to use anything in the zip file I uploaded containing D3's JS file?

**Comment by muenzpraeger** [comment]
Thanks @TannerJuby1 for the feedback.

_RE: Downloading the zip file and uploading as a static resource does not work as you suggest_
You can upload folders that you compressed. In that case you have to extend the path to the resource.

From [the documentation](https://developer.salesforce.com/docs/component-library/documentation/lwc/lwc.create_resources): `A static resource can be an archive file with a nested directory structure. To reference an item in an archive, concatenate a string to create the path to the item, as the example does to build einsteinUrl.`

_RE: You import the D3 resource as `D3` but then attempt to use `d3` all throughout the `initializeD3` method._
That's correct. Because `D3` is the static resource reference for loading the resources, but `d3` is the libraries own functionality.

_RE: In the `renderedCallback` method, you put `error.body.message` as the message to the toast event, but I continually get the error `undefined is not an object`._
Thanks for the feedback. I forwarded that to the documentation team. The correct value is `error.message` as [outlined](https://github.com/trailheadapps/lwc-recipes/blob/fc4a54d6c28910477271754e185f14a9857e3994/force-app/main/default/lwc/libsD3/libsD3.js#L31) in the code example.

_RE: all the other comments_
It seems that you have a general issue with loading the static resource. So I would start from there. [Here](https://developer.salesforce.com/blogs/2019/02/debug-your-lightning-web-components.html) is a good blog post about debugging LWC. And as you can see in [this code example](https://github.com/trailheadapps/lwc-recipes/blob/fc4a54d6c28910477271754e185f14a9857e3994/force-app/main/default/lwc/libsD3/libsD3.js#L31) we're using the same code as in docs (in fact the documentation got written based on our code example). And we use all the built-in functionality that you just mentioned. That's an implementation detail of `d3`.

**Comment by TannerJuby1** [comment]
Thanks @muenzpraeger for the quick response.

_RE: In that case you have to extend the path to the resource_: So by this you are saying that if I want to upload a compressed **folder**, say my folder is called `myD3`, my _loadScript_ method needs to look like: `loadScript(this, D3 + '/myD3/file.js');` rather than just `loadScript(this, D3 + '/file.js');`?

_RE: `D3` is a the static resource reference for loading resources, but `d3` is the libraries own functionality_: So When I attempt to use the code in the documentation, I just get the error `d3 is not defined`.. Why am I getting this error if this is the suggested usage?

_RE: error.message_ Thanks for this update, it did properly work.

_RE: loading the static resource._ I was able to get the resource to load properly finally after figuring out the zip issue, but now all my errors are stemming from the usage of `d3`. As I stated above, I get the error that `d3 is not defined`.

**Comment by TannerJuby1** [comment]
@muenzpraeger I was able to get the `d3 is not defined` to work by override the lint requirement via `/* eslint-disable no-undef */` at the top of the file. This may be worth a note within the documentation.

**Comment by muenzpraeger** [comment]
Good point, @TannerJuby1.

In the sample recipe we make use to define that `global` (see [here](https://github.com/trailheadapps/lwc-recipes/blob/fc4a54d6c28910477271754e185f14a9857e3994/force-app/main/default/lwc/libsD3/libsD3.js#L1)), so that the dedicated eslint comment isn't needed.
