### ISSUE TITLE
Error window.Chart is not a constructor when using libChartjs in LWR site

### ISSUE THREAD

**Issue by veaux** [trailheadapps/lwc-recipes#744]
### Summary

When using OOB libChartjs as component on LWR site charts will not preview. Component seems to work on Aura site.
For LWR site Error displays immediately after adding component in Experience Cloud Builder

```
Error retrieving data
Show details
window.Chart is not a constructor
```

### Salesforce Org Type

Scratch Org

### Steps To Reproduce

1. Create an LWR Experience Cloud site in any supported edition
2. Add <target>lightningCommunity_Page</target> to libsCharts.js
3. Add LibsChartjs component to a blank Experience Cloud page

### Current Behavior

Error displays
```
Error retrieving data
Show details
window.Chart is not a constructor
```

### Expected Behavior

Sample charts should generate.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adityanaag3** [comment]
Hi @veaux - This seems to be an issue with Lightning Locker on LWR Sites. Turning it off from the Security and Privacy section of the site settings resolves the issue.
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/11162785/215988700-49888646-9674-414a-928b-c33fd5949feb.png">

But, since Locker and CSP provide an additional layer of security to the site and your components, disabling/relaxing these settings must only be done after thoroughly evaluating the impact.

I have also raised this issue internally with the product teams and am waiting for a response from their end.

**Comment by adityanaag3** [comment]
Hey @veaux

There is a known limitation of Lightning Locker in LWR sites where the scripts loaded through [lightning/platformResourceLoader](https://developer.salesforce.com/docs/component-library/bundle/lightning-platform-resource-loader/documentation) run in system mode outside of a Lightning Locker sandbox. As a result, the component loading the script doesn’t have access to the same global variable scope as the script itself, preventing it from accessing any global variable set by the script.

To get around this restriction, we need to implement our own `loadScript` function. I have created a [PR](https://github.com/trailheadapps/lwc-recipes/pull/769) that adds this custom implementation to the recipes.  

Please add the `resourceLoader` component from this [PR](https://github.com/trailheadapps/lwc-recipes/pull/769) to your codebase, and use the below import statement to use the `loadScript` function from the custom `resourceLoader` module instead of the standard `lightning/platformResourceLoader`
```
import { loadScript } from 'c/resourceLoader';
```
